server:
  port: 7002

#spring:
#  redis:
#    default:
#      host: 121.199.173.153
#      port: 6379
#      password: 20240511
#      lettuce:
#        pool:
#          max-active: 8
#          max-wait: -1ms
#          max-idle: 8
#          min-idle: 0

config:
  evn:
    prefix: PROD
    test-diff: test1
  host-config:
    h5: h5.com
    app: app.com
    sys-admin: xjdAdmin.com
    dx-admin: dxAdmin.com
    dxm-admin: dxmAdmin.com
#图形验证码
security:
  captcha:
    enabled: true
    type: math



